
[Network]
  Address = ":6969"

[Server]
  AuthEnabled = true
  JoinMessage = "§l§a✔ %v"
  Name = "Velvet"
  QuitMessage = "§l§4✘ %v"
  ShutdownMessage = "Server closed."

[World]
  Folder = "worlds/world"
  Name = "World"

[Players]
  MaxCount = 0
  MaximumChunkRadius = 6
  SaveData = false
  Folder = "players"

[Resources]
  AutoBuildPack = false
  Folder = "resources"
  Required = true
