
[Network]
  Address = ":19132"

[Players]
  Folder = "players"
  MaxCount = 0
  MaximumChunkRadius = 6
  SaveData = false

[Resources]
  Folder = "resources_"

[Server]
  AuthEnabled = true
  JoinMessage = "ยงa[+] %v"
  Name = "Velvet"
  QuitMessage = "ยง4[-] %v"
  ShutdownMessage = "Server closed."

[World]
  Folder = "worlds/world"
  Name = "World"
