
[Network]
  Address = ":6969"

[Players]
  Folder = "players"
  MaxCount = 0
  MaximumChunkRadius = 6
  SaveData = false

[Resources]
  Folder = "resources_"

[Server]
  AuthEnabled = true
  JoinMessage = "§l§a✔ %v"
  Name = "Velvet"
  QuitMessage = "§l§4✘ %v"
  ShutdownMessage = "Server closed."

[World]
  Folder = "worlds/world"
  Name = "World"
