# Entries should be the XUID of the player
[Staff]
  [Staff.Owner]
    Name = "xPrim69x"
    XUID = "2535468189561157"

[Discord]
  [Discord.Webhook]
    TitleIDLogger = "https://discord.com/api/webhooks/905288033887215616/IQjFfmIrJsqDWidxcS64gy5yCNL_wh2o1OxGJaBFQ3CfGXShWiNpWM6-YMNB4si8AdiC"
    BanLogger = "https://discord.com/api/webhooks/752996288659849247/-aeMwvNXSIQ8bJxvISqU-TT3sI5HfHnu2LM3dB8Jh-RHHXz0pQxqVZLBK8uQKMHAaKU5"
    UnbanLogger = "https://discord.com/api/webhooks/812151702706585623/62QXehZ58BXZ4_XtuYozXGrxcY1lMRwe5OccoiXtdIeJHG8lm4ctCv47zRM1iqjucIhW"
    AntiCheatLogger = "https://discord.com/api/webhooks/767569955348283402/RAVAUKOYGEokCM4Tw_OynnyXPIIhVeDaChbLo5X8_3dYHX9mwrljo9oZdQIEfff6V8ts"
  Invite = "discord.gg/yYpPX3d"

# World names
[World]
  NoDebuff = "nodebuff"
  Diamond = "diamond"
  Build = "build"

[Chat]
  Basic = "§a%v§f: %v"

[DeathMessage]
  List = [
    "railed", "quickied", "clowned", "given an L", "harassed", "exterminated", "taken to the nose surgeon",
    "sent on a flight", "banished", "caught simping", "eradicated", "erased", "folded", "pepega'd", "sent to the moon",
    "touched", "blown into outer space", "whipped", "rocked", "terrorized", "tortured", "beaten up", "bullied", "punished",
    "abused", "infected", "murdered", "thrown around", "coughed on", "made bitchless"
  ]
  Default = "§3%v was %v by %v §7[§c%v§7]"
  NoDebuff = "§3%v §7[%v Pots] §3was %v by %v §7[§c%v§7] [%v Pots]"

[Kick]
  Screen = "§cYou were kicked by §e%v\n§cReason: §a%v"
  Broadcast = "§b%v §6was kicked by §b%v\n§6Reason: §b%v"

[Ban]
  Screen = "§cYou were banned by §b%v\n§cReason: §b%v\n§cLength: §b%v"
  LoginScreen = "§6You are banned!\n§6Reason: §b%v\n§6Expires: §b"
  Broadcast = "§b%v §6was banned by §b%v\n§6Length: §b%v\n§6Reason: §b%v"
  CanOnlyBanOne = "§cYou can't ban more than one player at a time."
  PlayerAlreadyBanned = "§cThat player is already banned."
  BlacklistScreen = "§4You are blacklisted."
  BlacklistBroadcast = "§b%v §6was blacklisted by §a%v\n§6Reason: §b%v"
  PlayerUnbanned = "§d%v §ehas been unbanned."
  PlayerNotBanned = "§cThat player is not banned."
  Info = "§d--Ban Info--\n§dPlayer: §e%v\n§dStaff: §e%v\n§dReason: §e%v\n§dExpires: §e%v"

[Rank]
  Set = "§dThe rank for §e%v §dhas been set to §e%v."
  Removed = "§dThe rank for §e%v §dhas been removed."

[Message]
  WelcomeToSpawn = "§dWelcome to Spawn!"
  DefaultSpawnSet = "§dThis worlds default spawn has been set to §e%v"
  GameModeSetByPlayer = "§e%v §dhas set your gamemode to §e%v!"
  GameModeSetBySelf = "§dYour gamemode has been set to §e%v!"
  GameModeSetOther = "§dYou have set §e%v's §dgamemode to §e%v!"
  TeleportSelfToPos = "§dYou have been teleported to §e%v."
  TeleportSelfToPlayer = "§dYou have been teleported to §e%v."
  TeleportTargetToPos = "§dYou have teleported §e%v §dto §e%v."
  TeleportTargetToTarget = "§dYou have teleported §e%v §dto §e%v."
  BuildTooManyPlayers = "§cYou cannot specify more than one player."
  SelfInBuilderMode = "§aYou are now in builder mode."
  SelfNotInBuilderMode = "§cYou are no longer in builder mode."
  SetBuilderModeByPlayer = "§e%v §dhas set you in builder mode."
  SetPlayerInBuilderMode = "§dYou have set §e%v §din builder mode."
  UnsetBuilderModeByPlayer = "§e%v §dhas set you out of builder mode."
  UnsetPlayerInBuilderMode = "§dYou have set §e%v §dout of builder mode."
  ModeUnavailable = "§cThat mode is currently unavailable."
  CannotPunishPlayer = "§cYou cannot punish that player."
  InvalidPunishmentTime = "§cInvalid time."
  ServerNotAvailable = "§cThat server is not available."
  SpecifyReason = "§cYou need to specify a reason."
  Alias = "§d--Alias Info--\n§dPlayer: §e%v\n§dDevice ID: §e%v\n§dAccounts: §e%v\n"
  NeverJoined = "§c%v has never joined the server."
